-- INSERT INTO users (username, email, password) VALUES ('user1', 'user1@gmail.com', 'asdf3ghj34kl');
-- INSERT INTO users (username, email, password) VALUES ('user2', 'user2@gmail.com', '1234567890');
