services:
  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234567890
      MARIADB_DATABASE: justphotons
    # ports:
    #   - "3306:3306"
  
  organisations:
    container_name: organisations
    build: ./organisations
    environment:
      DATABASE_URL: mariadb://db:3306/justphotons
    depends_on:
      - db
    restart: always
    ports:
      - "8082:8082"

  users:
    container_name: users
    build: ./users
    environment:
      DATABASE_URL: mariadb://db:3306/justphotons
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"

  image-files:
    container_name: image-files
    build: ./image-files
    environment:
      DB_ADDRESS: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234567890
      DB_NAME: justphotons
    depends_on:
      - db
    restart: always
    ports:
      - "8083:8080"

  image-metadata:
    container_name: image-metadata
    build: ./image-metadata
    environment:
      DB_ADDRESS: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234567890
      DB_NAME: justphotons
    depends_on:
      - db
    restart: always
    ports:
      - "8084:8080"

  permission-check:
    container_name: permission-check
    build: ./permission-check
    environment:
      DB_ADDRESS: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234567890
      DB_NAME: justphotons
    depends_on:
      - db
    restart: always
    ports:
      - "8085:8080"

  coordinator:
    container_name: coordinator
    build: ./coordinator
    environment:
      ORGANISATIONS_URL: http://organisations:8082/v1/organisations
      USERS_URL: http://users:8081/v1
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - '80:80'