services:
  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234567890
      MARIADB_DATABASE: organisations
    ports:
      - "3306:3306"
  
  organisations:
    build: ./organisations
    environment:
      DATABASE_URL: mariadb://db:3306/organisations
    depends_on:
      - db
    restart: always
    ports:
      - "8082:8082"