apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: coordinator
  name: coordinator
spec:
  selector:
    matchLabels:
      io.kompose.service: coordinator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: coordinator
    spec:
      containers:
        - resources:
            limits: 
              cpu: 500m
            requests: 
              cpu: 100m
          env:
          - name: IMAGES_URL
            value: http://image-files:8080/api/v1/images
          - name: METADATA_URL
            value: http://image-metadata:8080/api/v1/metadata
          - name: ORGANISATIONS_URL
            value: http://organisations:8082/v1/organisations
          - name: PERMISSIONS_URL
            value: http://permission-check:8080/api/v1/permissions
          - name: USERS_URL
            value: http://users:8081/v1
          image: banana4242/coordinator:latest
          name: coordinator
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuatr/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 2
            successThreshold: 1
      restartPolicy: Always
