apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules: 
  - http: 
      paths: 
        - path: /coordinator
          pathType: Prefix
          backend: 
            service: 
              name: coordinator
              port: 
                number: 8080
